/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Provider, TransactionRequest } from "@ethersproject/providers"
import { Contract, ContractFactory, Overrides, Signer, utils } from "ethers"
import type { Migrations, MigrationsInterface } from "../Migrations"

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "lastVersionContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "last_completed_migration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
]

const _bytecode =
  "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102cb806100606000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630900f01014610051578063445df0ac1461006d5780638da5cb5b1461008b578063c6e6e72e146100a9575b600080fd5b61006b600480360381019061006691906101c5565b6100c7565b005b610075610160565b6040516100829190610227565b60405180910390f35b610093610166565b6040516100a0919061020c565b60405180910390f35b6100b161018a565b6040516100be919061020c565b60405180910390f35b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561015d5780600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60015481565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000813590506101bf8161027e565b92915050565b6000602082840312156101d757600080fd5b60006101e5848285016101b0565b91505092915050565b6101f781610242565b82525050565b61020681610274565b82525050565b600060208201905061022160008301846101ee565b92915050565b600060208201905061023c60008301846101fd565b92915050565b600061024d82610254565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61028781610242565b811461029257600080fd5b5056fea264697066735822122038d0b0675cdeca9e08dabf879f2d6efdac100d4bf6644689e2e8e63f4baf491d64736f6c63430008040033"

type MigrationsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (
  xs: MigrationsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1

export class Migrations__factory extends ContractFactory
{
  constructor(...args: MigrationsConstructorParams)
  {
    if (isSuperArgs(args))
    {
      super(...args)
    } else
    {
      super(_abi, _bytecode, args[0])
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Migrations>
  {
    return super.deploy(overrides || {}) as Promise<Migrations>
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest
  {
    return super.getDeployTransaction(overrides || {})
  }
  override attach(address: string): Migrations
  {
    return super.attach(address) as Migrations
  }
  override connect(signer: Signer): Migrations__factory
  {
    return super.connect(signer) as Migrations__factory
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigrationsInterface
  {
    return new utils.Interface(_abi) as MigrationsInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Migrations
  {
    return new Contract(address, _abi, signerOrProvider) as Migrations
  }
}
